/* content.js — All data for the 5 games and 3 experiments. */
window.QUIZ_QUESTIONS = [
{q:"Acid là hợp chất mà phân tử gồm:",options:["Một hay nhiều nguyên tử hydrogen liên kết với gốc acid","Một nguyên tử oxygen","Một ion kim loại","Hai gốc base"],correct:0,
 explanation:"Acid: H + gốc acid. Ví dụ HCl, H₂SO₄, HNO₃, H₃PO₄."},
{q:"Base là hợp chất mà phân tử gồm:",options:["Một nguyên tử kim loại liên kết với một hay nhiều nhóm hydroxide (–OH)","Một nguyên tử hydrogen","Một gốc acid","Một oxide acid"],correct:0,
 explanation:"Base: kim loại + OH. Ví dụ NaOH, KOH, Ca(OH)₂, Fe(OH)₃."},
{q:"Muối là hợp chất mà phân tử gồm:",options:["Một hay nhiều nguyên tử kim loại liên kết với một hay nhiều gốc acid","Hai nguyên tử oxygen","Một acid mạnh","Một base mạnh"],correct:0,
 explanation:"Muối: kim loại + gốc acid. Ví dụ NaCl, K₂SO₄, CaCO₃, Cu(NO₃)₂."},
{q:"Oxide là hợp chất gồm:",options:["Hai nguyên tố, trong đó có một nguyên tố là oxygen","Hai kim loại","Một nguyên tố","Ba nguyên tố trở lên"],correct:0,
 explanation:"Oxide là hợp chất 2 nguyên tố, một trong đó là oxygen. Ví dụ Fe₂O₃, CO₂, SO₂."},
{q:"Cặp chất nào sau đây gồm một oxide acid và một oxide base?",options:["Na₂O và CaO","CO₂ và SO₂","SO₃ và CaO","K₂O và Fe₂O₃"],correct:2,
 explanation:"SO₃ là oxide acid (tương ứng H₂SO₄). CaO là oxide base (tương ứng Ca(OH)₂)."},
{q:"Dung dịch có pH = 3 là môi trường:",options:["Trung tính","Acid","Base","Không xác định"],correct:1,
 explanation:"pH < 7: acid; pH = 7: trung tính; pH > 7: base. pH = 3 → môi trường acid."},
{q:"Dung dịch có pH = 9 là môi trường:",options:["Acid","Trung tính","Base","Không xác định"],correct:2,
 explanation:"pH > 7 là môi trường base. pH = 9 nằm ở mức base nhẹ–trung bình."},
{q:"Quỳ tím chuyển sang màu đỏ khi gặp:",options:["Dung dịch base","Dung dịch acid","Dung dịch muối trung tính","Nước cất"],correct:1,
 explanation:"Acid → quỳ tím hóa đỏ. Base → hóa xanh. Muối trung tính/nước cất → không đổi."},
{q:"Phenolphtalein không màu chuyển sang màu hồng khi gặp:",options:["Acid","Base","Nước cất","Muối ăn"],correct:1,
 explanation:"Phenolphtalein hóa hồng trong base (pH ≥ 8,3); không màu trong acid/trung tính."},
{q:"Sản phẩm của phản ứng giữa NaOH và HCl là:",options:["NaCl và H₂O","Khí H₂","Khí O₂","Một base mới"],correct:0,
 explanation:"NaOH + HCl → NaCl + H₂O. Đây là phản ứng trung hòa: acid + base → muối + nước."},
{q:"Sản phẩm khi cho Zn tác dụng với HCl là:",options:["ZnCl₂ + H₂","ZnO + H₂O","Zn(OH)₂ + Cl₂","Không phản ứng"],correct:0,
 explanation:"Zn + 2HCl → ZnCl₂ + H₂↑. Phản ứng thế giữa kim loại và acid."},
{q:"Phản ứng nào sau đây tạo kết tủa?",options:["NaCl + KNO₃","AgNO₃ + NaCl","NaCl + H₂O","KCl + NaNO₃"],correct:1,
 explanation:"AgNO₃ + NaCl → AgCl↓ trắng + NaNO₃. AgCl không tan trong nước."},
{q:"Trong các muối sau, muối nào KHÔNG tan trong nước?",options:["NaCl","KNO₃","BaSO₄","KCl"],correct:2,
 explanation:"BaSO₄ là kết tủa trắng, không tan trong nước. NaCl, KNO₃, KCl đều tan tốt."},
{q:"Tên gọi của CuCl₂ là:",options:["Đồng(I) clorua","Đồng(II) clorua","Đồng oxit","Đồng hydroxide"],correct:1,
 explanation:"CuCl₂ = Copper(II) chloride / Đồng(II) clorua. Cu có hóa trị II ở đây."},
{q:"Tên gọi của Fe₂(SO₄)₃ là:",options:["Sắt(II) sulfate","Sắt(III) sulfate","Sắt sulfua","Sắt nitrat"],correct:1,
 explanation:"Fe₂(SO₄)₃ = Iron(III) sulfate. Fe có hóa trị III, gốc SO₄ hóa trị II → Fe₂(SO₄)₃."},
{q:"Hoàn thành: ZnO + HCl → ___",options:["ZnCl + H₂O","ZnCl₂ + H₂O","Zn + Cl₂ + H₂O","Zn(OH)₂"],correct:1,
 explanation:"ZnO + 2HCl → ZnCl₂ + H₂O. Oxide base + acid → muối + nước."},
{q:"Hoàn thành: P₂O₅ + 6KOH → ___",options:["2K₃PO₄ + 3H₂O","KPO₃ + H₂","K₂SO₄ + H₂O","K + PO₃"],correct:0,
 explanation:"P₂O₅ + 6KOH → 2K₃PO₄ + 3H₂O. Oxide acid + base → muối + nước."},
{q:"Phân đạm cung cấp nguyên tố nào cho cây?",options:["N (Nitrogen)","P (Phosphorus)","K (Potassium)","Ca (Calcium)"],correct:0,
 explanation:"Phân đạm cung cấp N, giúp cây phát triển thân lá. Ví dụ: urea, NH₄NO₃."},
{q:"Phân lân cung cấp nguyên tố:",options:["N","P","K","Mg"],correct:1,
 explanation:"Phân lân cung cấp phosphorus (P), giúp bộ rễ và ra hoa, kết quả."},
{q:"Phân kali cung cấp nguyên tố:",options:["Na","K","Ca","Fe"],correct:1,
 explanation:"Phân kali cung cấp potassium (K), tăng sức chống bệnh và phẩm chất nông sản."},
{q:"NPK là phân bón:",options:["Chỉ chứa N","Chỉ chứa K","Hỗn hợp chứa cả N, P, K","Phân vi lượng"],correct:2,
 explanation:"NPK là phân hỗn hợp chứa nitrogen, phosphorus, potassium — ba nguyên tố chính."},
{q:"Cho dung dịch NaOH tác dụng với CuSO₄, sản phẩm là:",options:["Cu(OH)₂ kết tủa xanh + Na₂SO₄","Cu + Na₂SO₄","CuO + Na₂SO₃","Không phản ứng"],correct:0,
 explanation:"2NaOH + CuSO₄ → Cu(OH)₂↓ (xanh) + Na₂SO₄. Phản ứng trao đổi tạo kết tủa."},
{q:"Trong chuỗi: S → SO₂ → ___ → NaCl, chất ở chỗ trống là:",options:["H₂S","Na₂SO₃","SO₃","NaOH"],correct:1,
 explanation:"S → SO₂ → Na₂SO₃ → NaCl: SO₂ + 2NaOH → Na₂SO₃; Na₂SO₃ + 2HCl → 2NaCl + H₂O + SO₂."},
{q:"Để điều chế Cu(OH)₂ trong PTN, ta có thể:",options:["Cho Cu tác dụng với H₂O","Cho dd CuSO₄ tác dụng với dd NaOH","Cho CuO tác dụng với HCl","Đốt Cu trong không khí"],correct:1,
 explanation:"CuSO₄ + 2NaOH → Cu(OH)₂↓ + Na₂SO₄. Cu không tác dụng với nước; CuO + HCl tạo CuCl₂."},
{q:"Phản ứng trao đổi giữa hai dung dịch xảy ra khi sản phẩm có:",options:["Khí thoát ra hoặc chất kết tủa hoặc nước","Hai chất tan trong nước","Một chất khí và một acid","Hai oxide"],correct:0,
 explanation:"Phản ứng trao đổi xảy ra khi tạo ra: kết tủa, khí, hoặc nước (chất ít phân ly)."},
{q:"Cho 2 dung dịch không nhãn NaOH và HCl, có thể dùng chất nào để nhận biết?",options:["Quỳ tím (NaOH hóa xanh, HCl hóa đỏ)","Nước cất","Đường","Muối ăn"],correct:0,
 explanation:"Quỳ tím là chỉ thị màu phổ biến: hóa xanh trong base, hóa đỏ trong acid."},
{q:"Cho khí CO₂ vào dung dịch nước vôi trong [Ca(OH)₂], hiện tượng quan sát:",options:["Dung dịch trong suốt","Tạo kết tủa trắng CaCO₃","Sủi bọt khí","Không có hiện tượng"],correct:1,
 explanation:"CO₂ + Ca(OH)₂ → CaCO₃↓ trắng + H₂O. Dùng để nhận biết CO₂."},
{q:"Hòa tan CaCO₃ vào dung dịch HCl, hiện tượng:",options:["Có khí CO₂ thoát ra, CaCO₃ tan","Không có hiện tượng","Tạo kết tủa","Khí O₂ thoát ra"],correct:0,
 explanation:"CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂↑. Sủi bọt khí CO₂."},
{q:"Khi pha loãng acid sulfuric đặc, để an toàn ta phải:",options:["Đổ nước vào acid","Đổ acid từ từ vào nước, vừa đổ vừa khuấy","Đổ cả hai cùng lúc","Không cần lưu ý gì"],correct:1,
 explanation:"QUY TẮC: rót acid đặc vào nước, vừa rót vừa khuấy. Ngược lại sẽ làm acid bắn nguy hiểm."},
{q:"Tỉ lệ %N trong urea CO(NH₂)₂ là (M=60):",options:["23,3%","35%","46,7%","60%"],correct:2,
 explanation:"m_N = 2·14 = 28; %N = 28/60 ≈ 46,7%. Urea là phân đạm có hàm lượng N cao nhất."},
{q:"Cho lá Al sạch vào dung dịch CuCl₂, hiện tượng:",options:["Không phản ứng","Al bị tan, Cu màu đỏ bám trên lá Al","Khí H₂ thoát ra","Tạo kết tủa trắng"],correct:1,
 explanation:"2Al + 3CuCl₂ → 2AlCl₃ + 3Cu. Al hoạt động hóa học mạnh hơn Cu nên đẩy Cu ra khỏi muối."}
];

window.CLASSIFY_ITEMS = [
{formula:"HCl", category:"acid"}, {formula:"H₂SO₄", category:"acid"},
{formula:"HNO₃", category:"acid"}, {formula:"H₃PO₄", category:"acid"},
{formula:"H₂CO₃", category:"acid"},
{formula:"NaOH", category:"base"}, {formula:"KOH", category:"base"},
{formula:"Ca(OH)₂", category:"base"}, {formula:"Mg(OH)₂", category:"base"},
{formula:"Cu(OH)₂", category:"base"},
{formula:"CO₂", category:"oxide"}, {formula:"SO₂", category:"oxide"},
{formula:"CaO", category:"oxide"}, {formula:"Na₂O", category:"oxide"},
{formula:"Fe₂O₃", category:"oxide"},
{formula:"NaCl", category:"muoi"}, {formula:"K₂SO₄", category:"muoi"},
{formula:"CaCO₃", category:"muoi"}, {formula:"CuCl₂", category:"muoi"},
{formula:"AgNO₃", category:"muoi"}
];
window.CLASSIFY_CATEGORIES = [
{id:"acid", label:"Acid", desc:"H + gốc acid", color:"#dc2626"},
{id:"base", label:"Base", desc:"Kim loại + OH", color:"#2563eb"},
{id:"oxide", label:"Oxide", desc:"Hai nguyên tố, có O", color:"#059669"},
{id:"muoi", label:"Muối", desc:"Kim loại + gốc acid", color:"#7c3aed"}
];

window.MATCH_PAIRS = [
{a:"HCl", b:"Acid hydrochloric"},
{a:"H₂SO₄", b:"Acid sulfuric"},
{a:"HNO₃", b:"Acid nitric"},
{a:"NaOH", b:"Sodium hydroxide"},
{a:"Ca(OH)₂", b:"Vôi tôi (Calcium hydroxide)"},
{a:"CaO", b:"Vôi sống (Calcium oxide)"},
{a:"CO₂", b:"Carbon dioxide"},
{a:"NaCl", b:"Muối ăn (Sodium chloride)"},
{a:"CaCO₃", b:"Đá vôi (Calcium carbonate)"},
{a:"KNO₃", b:"Potassium nitrate"}
];

window.BALANCE_EQUATIONS = [
{terms:[{f:"Al"},{f:"HCl"},{f:"AlCl₃"},{f:"H₂"}], coeffs:[2,6,2,3], arrowAt:2, note:"Phản ứng thế: kim loại + acid"},
{terms:[{f:"Fe"},{f:"O₂"},{f:"Fe₂O₃"}], coeffs:[4,3,2], arrowAt:2, note:"Phản ứng hóa hợp: oxi hóa kim loại"},
{terms:[{f:"NaOH"},{f:"H₂SO₄"},{f:"Na₂SO₄"},{f:"H₂O"}], coeffs:[2,1,1,2], arrowAt:2, note:"Phản ứng trung hòa: base + acid"},
{terms:[{f:"CaCO₃"},{f:"HCl"},{f:"CaCl₂"},{f:"H₂O"},{f:"CO₂"}], coeffs:[1,2,1,1,1], arrowAt:2, note:"Muối + acid → muối mới + nước + khí"},
{terms:[{f:"P₂O₅"},{f:"H₂O"},{f:"H₃PO₄"}], coeffs:[1,3,2], arrowAt:2, note:"Oxide acid + nước → acid"},
{terms:[{f:"KOH"},{f:"CuSO₄"},{f:"Cu(OH)₂"},{f:"K₂SO₄"}], coeffs:[2,1,1,1], arrowAt:2, note:"Trao đổi tạo kết tủa Cu(OH)₂"},
{terms:[{f:"Mg"},{f:"HNO₃"},{f:"Mg(NO₃)₂"},{f:"H₂"}], coeffs:[1,2,1,1], arrowAt:2, note:"Kim loại + acid → muối + H₂"},
{terms:[{f:"Ba(OH)₂"},{f:"H₂SO₄"},{f:"BaSO₄"},{f:"H₂O"}], coeffs:[1,1,1,2], arrowAt:2, note:"Trung hòa tạo kết tủa BaSO₄"}
];

window.PH_ITEMS = [
{name:"HCl 0,1M", ph:1},
{name:"Nước chanh", ph:2},
{name:"Giấm ăn", ph:3},
{name:"Cà phê", ph:5},
{name:"Sữa tươi", ph:6},
{name:"Nước cất", ph:7},
{name:"Máu người", ph:7},
{name:"Nước biển", ph:8},
{name:"Baking soda", ph:9},
{name:"Xà phòng", ph:10},
{name:"NH₃ đặc", ph:11},
{name:"NaOH 0,1M", ph:13}
];
