/* glossary.js - Vietnamese -> English chemistry & general dictionary.
   Each entry: [vi, en, type?]. type "common" = soft underline. */
window.GLOSSARY = [
["định luật bảo toàn khối lượng","law of conservation of mass"],
["phản ứng oxi hóa - khử","redox reaction"],
["phản ứng oxi hóa-khử","redox reaction"],
["phản ứng hóa hợp","combination reaction"],
["phản ứng phân hủy","decomposition reaction"],
["phản ứng trao đổi","exchange / metathesis reaction"],
["phản ứng trung hòa","neutralization reaction"],
["phản ứng thế","substitution / displacement reaction"],
["phản ứng hóa học","chemical reaction"],
["phản ứng","reaction"],
["phương trình hóa học","chemical equation"],
["phương trình","equation"],
["hiện tượng hóa học","chemical change / phenomenon"],
["hiện tượng vật lý","physical change / phenomenon"],
["hiện tượng","phenomenon"],
["bảo toàn khối lượng","conservation of mass"],
["bảo toàn","conservation"],
["chất phản ứng","reactant"],
["chất sản phẩm","product"],
["sản phẩm","product"],
["chất xúc tác","catalyst"],
["chất khử","reducing agent"],
["chất oxi hóa","oxidizing agent"],
["chất tan","solute"],
["chất khí","gas (substance)"],
["chất lỏng","liquid (substance)"],
["chất rắn","solid (substance)"],
["chất nguyên chất","pure substance"],
["chất mới","new substance"],
["chất","substance"],
["dung môi","solvent"],
["dung dịch bão hòa","saturated solution"],
["dung dịch chưa bão hòa","unsaturated solution"],
["dung dịch","solution"],
["hỗn hợp đồng nhất","homogeneous mixture"],
["hỗn hợp","mixture"],
["hợp chất","compound"],
["đơn chất","elementary substance"],
["nguyên tố","element"],
["nguyên tử","atom"],
["phân tử","molecule"],
["kim loại","metal"],
["phi kim","non-metal"],
["khí hiếm","noble gas"],
["chỉ thị màu","indicator"],
["chỉ thị","indicator"],
["quỳ tím","litmus paper"],
["phenolphtalein","phenolphthalein"],
["gốc acid","acid radical"],
["gốc","radical / root"],
["nhóm hydroxide","hydroxide group (-OH)"],
["nhóm","group"],
["liên kết","chemical bond"],
["công thức hóa học","chemical formula"],
["công thức","formula"],
["oxide acid","acidic oxide"],
["oxide base","basic oxide"],
["oxide","oxide"],
["acid","acid"],
["base","base / alkali"],
["muối ăn","table salt (NaCl)"],
["muối trung tính","neutral salt"],
["muối","salt"],
["nước cất","distilled water"],
["nước","water (H2O)"],
["không khí","air"],
["oxygen","oxygen (O2)"],
["hydrogen","hydrogen (H2)"],
["nitrogen","nitrogen (N2)"],
["carbon dioxide","carbon dioxide (CO2)"],
["sulfur dioxide","sulfur dioxide (SO2)"],
["sulfur","sulfur"],
["lưu huỳnh","sulfur (S)"],
["phosphorus","phosphorus (P)"],
["chlorine","chlorine (Cl2)"],
["methane","methane (CH4)"],
["urea","urea CO(NH2)2"],
["vôi tôi","slaked lime"],
["vôi sống","quicklime"],
["amoni nitrat","ammonium nitrate"],
["khối lượng mol","molar mass"],
["khối lượng phân tử","molecular mass"],
["khối lượng","mass"],
["thể tích","volume"],
["nhiệt độ thường","room temperature"],
["nhiệt độ","temperature"],
["áp suất","pressure"],
["độ tan","solubility"],
["nồng độ phần trăm","mass percent"],
["nồng độ mol","molar concentration"],
["nồng độ","concentration"],
["pha loãng","dilution"],
["số mol","amount in moles"],
["mol","mole"],
["đktc","standard conditions (STP)"],
["tính khử","reducing property"],
["tính oxi hóa","oxidizing property"],
["tính chất vật lý","physical property"],
["tính chất hóa học","chemical property"],
["tính chất","property"],
["tỉ lệ","ratio"],
["phần trăm","percent (%)"],
["thành phần","composition"],
["hàm lượng","content / percentage"],
["hệ số","coefficient"],
["hiệu suất","yield (%)"],
["sự cháy","combustion"],
["sự oxi hóa chậm","slow oxidation"],
["sự oxi hóa","oxidation"],
["oxi hóa","oxidize"],
["khử","reduce / reduction"],
["điều chế","preparation"],
["điện phân","electrolysis"],
["chưng cất","distillation"],
["kết tủa","precipitate"],
["bay hơi","evaporate"],
["nóng chảy","melt / melting"],
["ngưng tụ","condense"],
["sôi","boil / boiling"],
["thí nghiệm","experiment"],
["phòng thí nghiệm","laboratory"],
["ptn","laboratory (PTN)"],
["đun nóng","heat up"],
["đun","heat"],
["nung","calcine"],
["đốt cháy","burn / combust"],
["đốt","burn"],
["hòa tan","dissolve"],
["bão hòa","saturate"],
["trung hòa","neutralize"],
["tỏa nhiệt","exothermic / release heat"],
["thu nhiệt","endothermic / absorb heat"],
["tỏa","release"],
["thoát ra","be released"],
["thoát","escape"],
["sinh ra","produce"],
["tạo thành","form"],
["tạo ra","produce"],
["tạo","form / create"],
["thay đổi","change"],
["tác dụng","react with"],
["cháy","burn"],
["đổi màu","change color"],
["phân bón hóa học","chemical fertilizer"],
["phân bón","fertilizer"],
["phân đạm","nitrogen fertilizer"],
["phân lân","phosphate fertilizer"],
["phân kali","potassium fertilizer"],
["phân vi lượng","micronutrient fertilizer"],
["phân hữu cơ","organic fertilizer"],
["bón phân","apply fertilizer"],
["bón","fertilize"],
["phú dưỡng","eutrophication"],
["độ phì","soil fertility"],
["nông sản","agricultural produce"],
["nông dân","farmer"],
["dấu hiệu","sign / indicator"],
["sủi bọt","bubbles forming"],
["bọt khí","gas bubbles"],
["mùi hắc","pungent smell"],
["khói trắng","white smoke"],
["nhiệt năng","thermal energy"],
["nhiệt","heat"],
["khí","gas"],
["lỏng","liquid"],
["rắn","solid"],
["hơi nước","water vapor"],
["hơi","vapor / steam"],
["môi trường acid","acidic environment"],
["môi trường base","basic environment"],
["môi trường trung tính","neutral environment"],
["môi trường","environment / medium"],
["sự hô hấp","respiration"],
["loãng","dilute"],
["đặc","concentrated"],
["tinh khiết","pure"],
["nguyên chất","pure"],
["đồng nhất","homogeneous"],
["an toàn","safety / safe"],
["nguy hiểm","dangerous"],
["kính bảo hộ","safety goggles"],
["tủ hốt","fume hood"],
["bộ rễ","root system"],
["cây","plant / tree","common"],
["loại","type / kind","common"],
["lượng","amount","common"],
["số","number","common"],
["tổng","total","common"],
["phần","part","common"],
["cách","way / manner","common"],
["ví dụ","example","common"],
["màu sắc","color","common"],
["màu đỏ","red","common"],
["màu xanh","blue / green","common"],
["màu hồng","pink","common"],
["màu vàng","yellow","common"],
["màu trắng","white","common"],
["màu đen","black","common"],
["màu","color","common"],
["mùi","smell / odor","common"],
["thường","usually","common"],
["định nghĩa","definition","common"],
["khái niệm","concept","common"],
["phát biểu","statement","common"],
["dụng cụ","apparatus","common"],
["cốc","cup / beaker","common"],
["chai","bottle","common"],
["nắp","cap / lid","common"],
["nhà","house","common"],
["đất","soil / earth","common"],
["nguồn","source","common"],
["cung cấp","supply / provide","common"],
["sử dụng","use","common"],
["dùng","use","common"],
["thêm","add","common"],
["tăng","increase","common"],
["giảm","decrease","common"],
["mở","open","common"],
["đóng","close","common"],
["đổ","pour","common"],
["trộn","mix","common"],
["khuấy","stir","common"],
["quan sát","observe","common"],
["nhận biết","identify","common"],
["phân biệt","distinguish","common"],
["cân bằng","balance","common"],
["tính","calculate","common"],
["chứa","contain","common"],
["gồm","consist of","common"],
["bao gồm","include","common"],
["bằng","equal to / by","common"],
["xảy ra","happen","common"],
["đo","measure","common"],
["nhận","receive","common"],
["mất","lose","common"],
["bị","be (passive)","common"],
["được","be / get / can","common"],
["mạnh","strong","common"],
["yếu","weak","common"],
["nặng","heavy","common"],
["nhẹ","light (weight)","common"],
["lớn","big / large","common"],
["nhỏ","small","common"],
["nhanh","fast","common"],
["chậm","slow","common"],
["nhiều","many / much","common"],
["ít","few / little","common"],
["đủ","enough","common"],
["dư","excess","common"],
["thiếu","lack","common"],
["mới","new","common"],
["cũ","old","common"],
["khác","different","common"],
["giống","same / similar","common"],
["đúng","correct / right","common"],
["sai","wrong / incorrect","common"],
["tốt","good","common"],
["hợp lý","reasonable","common"],
["bền vững","sustainable","common"],
["nhất","most","common"],
["hơn","more than","common"],
["rất","very","common"],
["chỉ","only","common"],
["có thể","can / may","common"],
["không thể","cannot","common"],
["luôn","always","common"],
["sau","after","common"],
["trước","before","common"],
["cuối","last / end","common"],
["đầu","first / head","common"],
["không","no / not","common"],
["có","have / there is","common"],
["là","is / to be","common"],
["của","of","common"],
["và","and","common"],
["hoặc","or","common"],
["với","with","common"],
["nếu","if","common"],
["khi","when","common"],
["vì","because","common"],
["do","due to","common"],
["nhưng","but","common"],
["tuy nhiên","however","common"],
["để","in order to","common"],
["trong","in / inside","common"],
["ngoài","outside","common"],
["trên","on / above","common"],
["dưới","below","common"],
["giữa","between","common"],
["vào","into","common"],
["ra","out","common"],
["lên","up","common"],
["xuống","down","common"],
["sang","across / over","common"],
["theo","according to","common"],
["từ","from","common"],
["đến","to / arrive","common"],
["cho","to / for / give","common"],
["bởi","by","common"],
["sau đó","after that","common"],
["sau khi","after","common"],
["trước khi","before","common"],
["cùng","together","common"],
["mỗi","each / every","common"],
["mọi","every","common"],
["một","one / a","common"],
["hai","two","common"],
["ba","three","common"],
["bốn","four","common"],
["các","the / various","common"],
["này","this","common"],
["đó","that","common"],
["nào","which","common"],
["sau đây","below / following","common"],
["còn","still / and","common"],
["sẽ","will (future)","common"],
["đã","already (past)","common"],
["đang","be doing (progressive)","common"],
["lại","again","common"],
["nơi","place","common"],
["đâu","where","common"],
["thế","thus / so","common"],
["sao","why / how","common"],
["lửa","fire / flame","common"],
["ngọn lửa","flame","common"],
["đám cháy","fire / blaze","common"],
["dập tắt","extinguish","common"],
["duy trì","maintain","common"],
["cách ly","isolate","common"],
["ô nhiễm","pollution","common"],
["hậu quả","consequence","common"],
["gây","cause","common"],
["lạm dụng","abuse / overuse","common"],
["dư lượng","residue","common"],
["độc","toxic","common"],
["chai cứng","compact (soil)","common"],
["thuộc loại","belong to","common"],
["thuộc","belong to","common"],
["bài toán","problem","common"],
["công nghiệp","industry","common"],
["sản xuất","produce","common"],
["áp dụng","apply","common"]
];
